### ISSUE TITLE
Using NestedGenericStackedPolymorphicInline gives me AttributeError: 'str' object has no attribute '_meta' exception

### ISSUE THREAD

**Issue by bashu** [theatlantic/django-nested-admin#184]
Go to https://github.com/theatlantic/django-nested-admin/blob/master/nested_admin/tests/nested_polymorphic/test_polymorphic_add_filtering/models.py#L40

replace 
```python
    question = ForeignKey(Question, on_delete=NON_POLYMORPHIC_CASCADE)
```
with 
```python
    content_type = models.ForeignKey(
        ContentType, verbose_name=_("content type"),
        related_name="content_type_set_for_%(class)s",
        on_delete=models.CASCADE,
    )
    object_id = models.TextField(_("object ID"))
    content_object = GenericForeignKey(ct_field="content_type", fk_field="object_id")
```

then go to https://github.com/theatlantic/django-nested-admin/blob/master/nested_admin/tests/nested_polymorphic/test_polymorphic_add_filtering/admin.py#L80

and replace
```python
class QuestionInline(nested_admin.NestedStackedPolymorphicInline):
    class FreeTextInline(nested_admin.NestedStackedPolymorphicInline.Child):
        ...
    class PollInline(nested_admin.NestedStackedPolymorphicInline.Child):
        ...
```
with
```python
class QuestionInline(nested_admin.NestedGenericStackedPolymorphicInline):
    class FreeTextInline(nested_admin.NestedGenericStackedPolymorphicInline.Child):
        ...
    class PollInline(nested_admin.NestedGenericStackedPolymorphicInline.Child):
        ...
```

and voila you got this exception:

```python
Traceback (most recent call last):
...
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 858, in _resolve_lookup
    current = current()
  File "/usr/local/lib/python3.8/site-packages/nested_admin/polymorphic.py", line 80, in inline_formset_data
    'parentModel': get_model_id(formset_fk_model),
  File "/usr/local/lib/python3.8/site-packages/nested_admin/polymorphic.py", line 56, in get_model_id
    opts = model_cls._meta
AttributeError: 'str' object has no attribute '_meta'
```

**Comment by michaldyczko** [comment]
@bashu can you tell us if you solved it and how?
