### ISSUE TITLE
AttributeError: 'list' object has no attribute '_meta'

### ISSUE THREAD

**Issue by nabil-ha** [theatlantic/django-nested-admin#206]
Hey,
To be clear about what I'm doing, I chose nested_admin because I need to make a Course object, inside it a Part object, ( Part one, two and so on ) and each Part obj will have a File object
I get this error after opening an object of a model:
Internal Server Error: /admin/knowledgechanger_app/course/1/change/
```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/contrib/admin/options.py", line 616, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/contrib/admin/sites.py", line 232, in inner
    return view(request, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1660, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1540, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1604, in _changeform_view
    formsets, inline_instances = self._create_formsets(request, obj, change=True)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/nested_admin/nested.py", line 336, in _create_formsets
    in orig_inline.get_inline_instances(request, obj)]
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/contrib/admin/options.py", line 599, in get_inline_instances
    inline = inline_class(self.model, self.admin_site)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/nested_admin/nested.py", line 507, in __init__
    super(NestedInlineModelAdminMixin, self).__init__(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/contrib/admin/options.py", line 2024, in __init__
    self.opts = self.model._meta
AttributeError: 'list' object has no attribute '_meta'
```
my admin.py:
```

class ToFileInline(nested_admin.NestedStackedInline):
    model = [FileToPart]

class ToPartInline(nested_admin.NestedInlineModelAdmin):
    model = CoursePart
    inlines = [ToFileInline]

class CourseAdmin(nested_admin.NestedModelAdmin):
    model = Course
    inlines = [ToPartInline]



```

my models.py:

```
class Course(models.Model):
    # video = models.FileField(verbose_name="", null=True, upload_to='media')
    courseName = models.CharField(verbose_name="", max_length=20)
    category = models.ForeignKey(Category, verbose_name="", on_delete=models.SET_NULL, null=True)
    intro = models.CharField(verbose_name="", max_length=1000)
    skills = models.CharField(verbose_name="", max_length=1000)
    features = models.CharField(verbose_name="", max_length=1000)
    rate = models.FloatField(verbose_name="")
    class Meta:
        verbose_name = ""
        verbose_name_plural = ""



class CoursePart(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    name = models.CharField("", max_length=20)
    
class FileToPart(models.Model):
    coursePart = models.ForeignKey(CoursePart, on_delete=models.CASCADE)
    file = models.FileField(verbose_name="")
```

**Comment by fdintino** [comment]
Try removing the square brackets here:

```python
class ToFileInline(nested_admin.NestedStackedInline):
    model = [FileToPart]
```

changing it to:

```python
class ToFileInline(nested_admin.NestedStackedInline):
    model = FileToPart
```

**Comment by nabil-ha** [comment]
Thank you so much! it solved the issue.
