### ISSUE TITLE
ValidationError if extra=0

### ISSUE THREAD

**Issue by dimoha** [theatlantic/django-nested-admin#72]
If extra = 0 and all levels of nested objects saved, then i catch exception when try add another object to first level.

if extra=1 everything is fine.

**Comment by fdintino** [comment]
Could you provide more information about the exception you are getting, ideally a stack trace? I don't think I could reproduce this issue with the level of detail provided.

**Comment by dimoha** [comment]
Internal Server Error: /admin/core/questionnaire/9/change/
Traceback (most recent call last):
  File "/home/dimoha/.Envs/mysteryshopper/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/home/dimoha/.Envs/mysteryshopper/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/dimoha/.Envs/mysteryshopper/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/dimoha/.Envs/mysteryshopper/local/lib/python2.7/site-packages/django/contrib/admin/options.py", line 544, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/dimoha/.Envs/mysteryshopper/local/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/dimoha/.Envs/mysteryshopper/local/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/dimoha/.Envs/mysteryshopper/local/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 211, in inner
    return view(request, *args, **kwargs)
  File "/home/dimoha/.Envs/mysteryshopper/local/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/home/dimoha/.Envs/mysteryshopper/local/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/dimoha/.Envs/mysteryshopper/local/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/home/dimoha/.Envs/mysteryshopper/local/lib/python2.7/site-packages/django/utils/decorators.py", line 185, in inner
    return func(*args, **kwargs)
  File "/home/dimoha/.Envs/mysteryshopper/local/lib/python2.7/site-packages/nested_inline/admin.py", line 295, in change_view
    if self.all_valid_with_nesting(formsets) and form_validated:
  File "/home/dimoha/.Envs/mysteryshopper/local/lib/python2.7/site-packages/nested_inline/admin.py", line 138, in all_valid_with_nesting
    if not self.all_valid_with_nesting(form.nested_formsets):
  File "/home/dimoha/.Envs/mysteryshopper/local/lib/python2.7/site-packages/nested_inline/admin.py", line 130, in all_valid_with_nesting
    if not all_valid(formsets):
  File "/home/dimoha/.Envs/mysteryshopper/local/lib/python2.7/site-packages/django/forms/formsets.py", line 456, in all_valid
    if not formset.is_valid():
  File "/home/dimoha/.Envs/mysteryshopper/local/lib/python2.7/site-packages/django/forms/formsets.py", line 321, in is_valid
    self.errors
  File "/home/dimoha/.Envs/mysteryshopper/local/lib/python2.7/site-packages/django/forms/formsets.py", line 295, in errors
    self.full_clean()
  File "/home/dimoha/.Envs/mysteryshopper/local/lib/python2.7/site-packages/django/forms/formsets.py", line 343, in full_clean
    form = self.forms[i]
  File "/home/dimoha/.Envs/mysteryshopper/local/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/dimoha/.Envs/mysteryshopper/local/lib/python2.7/site-packages/django/forms/formsets.py", line 144, in forms
    for i in range(self.total_form_count())]
  File "/home/dimoha/.Envs/mysteryshopper/local/lib/python2.7/site-packages/django/forms/models.py", line 891, in _construct_form
    form = super(BaseInlineFormSet, self)._construct_form(i, **kwargs)
  File "/home/dimoha/.Envs/mysteryshopper/local/lib/python2.7/site-packages/django/forms/models.py", line 591, in _construct_form
    pk = to_python(pk)
  File "/home/dimoha/.Envs/mysteryshopper/local/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 927, in to_python
    params={'value': value},
ValidationError: [u"\u0417\u043d\u0430\u0447\u0435\u043d\u0438\u0435 '' \u0434\u043e\u043b\u0436\u043d\u043e \u0431\u044b\u0442\u044c \u0446\u0435\u043b\u044b\u043c \u0447\u0438\u0441\u043b\u043e\u043c."]

**Comment by fdintino** [comment]
I am unable to reproduce this. Could you share a minimal example models.py and admin.py that exhibits the problem?
